grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3

model_selection:
  modules_0: 
  class: KNeighborclassifier
  module: sklearn.neighbors
  params: 
    algorithm: kd_tree
    weights: uniform
    n_neighbors: 3
  search_params_grid:
    algorithm:
    - auto
    - ball_tree
    - kd_tree
    - brute
    weights:
    - uniform
    - distance
    n_neighbors:
    - 3
    - 5
    - 9

model_selection:
  modules_1: 
  class: RandomForestclassifier
  module: sklearn.ensemble
  params: 
    max_depth: 10
    max_features: sqrt
    n_estimator: 3  
  search_params_grid:
    max_depth:
    - 10
    - 15
    - 20
    max_features:
    - sqrt
    - log2
    n_estimators:
    - 3
    - 5
    - 9